-- ADR-007: IBFT_FREEZE / IBFT_SETTLE / IBFT_RELEASE wallet TX types (UC-5)
ALTER TABLE wallet.wallet_tx DROP CONSTRAINT IF EXISTS wallet_tx_tx_type_check;
ALTER TABLE wallet.wallet_tx ADD CONSTRAINT wallet_tx_tx_type_check CHECK (tx_type::text = ANY (ARRAY[
    'DEPOSIT_CREDIT','PAYMENT_DEBIT','PAYMENT_CREDIT',
    'TRANSFER_DEBIT','TRANSFER_CREDIT',
    'WITHDRAW_FREEZE','WITHDRAW_RELEASE','WITHDRAW_SETTLE',
    'IBFT_FREEZE','IBFT_RELEASE','IBFT_SETTLE',
    'ADJUSTMENT_CREDIT','ADJUSTMENT_DEBIT'
]::text[]));
