INSERT INTO accounting.coa_account (code, name, account_type, active) VALUES
    ('1111', 'Vietinbank — dedicated', 'ASSET', true),
    ('1112', 'Napas Clearing', 'ASSET', true),
    ('1113', 'VPBank — QR/POS', 'ASSET', true),
    ('2110', 'Wallet balance — User', 'LIABILITY', true),
    ('2120', 'Wallet balance — Merchant', 'LIABILITY', true),
    ('2130', 'Escrow — Disbursement partner', 'LIABILITY', true),
    ('3100', 'Transit — deposit', 'TRANSIT', true),
    ('3200', 'Transit — withdraw', 'TRANSIT', true),
    ('3300', 'Transit — internal transfer', 'TRANSIT', true),
    ('3400', 'Transit — IBFT', 'TRANSIT', true),
    ('3500', 'Transit — payment', 'TRANSIT', true),
    ('3600', 'Transit — payroll', 'TRANSIT', true),
    ('3700', 'Transit — disbursement', 'TRANSIT', true),
    ('3800', 'Transit — clearing', 'TRANSIT', true),
    ('3810', 'Transit — settlement outbound', 'TRANSIT', true),
    ('3820', 'Transit — MDR holdback', 'TRANSIT', true),
    ('4110', 'Fee revenue — deposit', 'REVENUE', true),
    ('4120', 'Fee revenue — withdraw', 'REVENUE', true),
    ('4130', 'Fee revenue — transfer', 'REVENUE', true),
    ('4140', 'Fee revenue — MDR', 'REVENUE', true),
    ('4150', 'Fee revenue — payroll / disbursement', 'REVENUE', true),
    ('5100', 'Bank / Napas fee expense', 'EXPENSE', true),
    ('6000', 'Owner''s equity', 'EQUITY', true);
