spring.application.name=app-orchestration

orchestration.http.port=8080

spring.datasource.url=jdbc:h2:mem:gtelpay;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

spring.flyway.enabled=false

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
